<a href="https://colab.research.google.com/github/Luna0414/-DSC_110-/blob/main/ML_Data_Prep_10_27_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
#just selecting 3 specific things for the libary instead of using the whole libary to save storage
#make sure standard and scaler have captial S
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/osoliman/DSC110/refs/heads/main/Datasets/nhanes_final.csv')

In [5]:
df.head()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN

Step 1: filtering

In [6]:
df = df[df['age'] >=18]
#add space between to make it each step readable

In [7]:
#getting minimum
df['age'].min()

18.0

Step 2: drop colums/fields

> Drop irrelevant fields e.g., id and fields that are not avabblie at the time of predicting hbalc

In [23]:
#dropping any fields that are not relevant
# [] for the list
#if you run too many times it can give you an error
df = df.drop(columns=['id', 'hba1c', 'fasting_glucose'], errors='ignore')

In [11]:
#check with df.head() if you get error to check if data was removed
# 3 and 4 where removed
df.head()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
6,130384.0,1.0,43.0,1.0,2.0,NaN,NaN,NaN,2.0,NaN,NaN
7,130385.0,2.0,65.0,3.0,3.0,NaN,NaN,NaN,2.0,NaN,NaN

Step 3: mapping labels

In [13]:
#creating dictionaries
gender_map = {1.0: 'male', 2.0: 'female'}
df['gender'] = df['gender'].map(gender_map)

In [14]:
df['gender'].value_counts()

gender
female    4496
male      3657
Name: count, dtype: int64

In [15]:
#education
education_map = {
    1.0: 'less than 9th',
    2.0: '9th-11th grade',
    3.0: 'high school',
    4.0: 'some college',
    5.0: 'college grad',
    9.0: 'do not know'
}

In [16]:
df['education'] = df['education'].map(education_map)

In [17]:
df['education'].value_counts()

education
college grad      2625
some college      2370
high school       1749
9th-11th grade     666
less than 9th      373
do not know         11
Name: count, dtype: int64

In [22]:
#race_ethnicity mapping
#dictionary = {}
race_map = {
    1.0: 'Mexican American',
    2.0: 'Other Hispanic',
    3.0: 'White',
    4.0: 'Black',
    6.0: 'Asian',
    7.0: 'Other'
}
df['race_ethnicity'] = df['race_ethnicity'].map(race_map)
df['race_ethnicity'].value_counts()

race_ethnicity
White               4704
Black               1045
Other Hispanic       819
Mexican American     598
Other                544
Asian                443
Name: count, dtype: int64

Step 4: missing values

In [25]:
#checking missing values
df.isna().sum()

gender               0
age                  0
race_ethnicity       0
education          359
bmi               1918
height_cm         1891
systolic_bp       2030
has_diabetes         3
dtype: int64

In [27]:
#a loop used instead of repeating this; df['bmi'] = df['bmi'].fillina
for col in ['bmi', 'height_cm', 'systolic_bp']:
  df[col] =df[col].fillna(df[col].mean())

In [28]:
df.isna().sum()

gender              0
age                 0
race_ethnicity      0
education         359
bmi                 0
height_cm           0
systolic_bp         0
has_diabetes        3
dtype: int64

In [29]:
#removing rows where education is missing
# dropna =drops fields of values
df = df.dropna(subset=['education'])

In [30]:
#now theres no missing values
df.isna().sum()

gender            0
age               0
race_ethnicity    0
education         0
bmi               0
height_cm         0
systolic_bp       0
has_diabetes      0
dtype: int64

Step 5: define the target

In [31]:
# step 1: include only rows that have diabetes yes or no
#removing raws where diabetes is borderlineg or missing
df = df[df['has_diabetes'].isin([1.0,2.0])]

In [32]:
df['has_diabetes'].value_counts()
#2.0= no diabetes
#1.0= had diabetes

has_diabetes
2.0    6455
1.0    1068
Name: count, dtype: int64

In [33]:
df['has_diabetes'] = df['has_diabetes'].map({
    1.0: 1,
    2.0: 0,
})