<a href="https://colab.research.google.com/github/Luna0414/-DSC_110-/blob/main/week5_pandas_10_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas**

In [35]:
import pandas as pd

# **Loading files**

In [36]:
#add the link to dataset from a CSV file into a pandas dataframe
# The dataframe is stored in the variable 'df' for data manipulation

df = pd.read_csv('https://raw.githubusercontent.com/osoliman/DSC110/refs/heads/main/Datasets/nhanes_final.csv')

# **Operations on Data Frames**

In [37]:
#show top 5 rows
df.head()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN

In [38]:
df.head(1)

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0

In [39]:
df.tail()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
11928,142306.0,1.0,9.0,2.0,NaN,15.4,128.0,NaN,2.0,NaN,NaN
11929,142307.0,2.0,49.0,4.0,5.0,NaN,143.8,127.0,1.0,6.2,NaN
11930,142308.0,1.0,50.0,2.0,4.0,26.4,173.3,106.0,2.0,NaN,NaN
11931,142309.0,1.0,40.0,2.0,4.0,25.5,179.1,127.0,2.0,5.2,96.0
11932,142310.0,2.0,80.0,3.0,3.0,27.6,161.7,128.0,2.0,5.3,NaN

In [40]:
df.shape

(11933, 11)

In [41]:
df.shape[0]

11933

In [42]:
print(f'this file has {df.shape[0]} rows and {df.shape[1]} columns')

this file has 11933 rows and 11 columns

# **Data Cleaning**

Missing Values
- Find fields with missing values
- Drop missing values
- Replace missing values with mean

In [43]:
#Boolean
1+1==2

True

In [44]:
1+1==3

False

In [45]:
int(True)

1

In [46]:
int(1+1==2)

1

In [47]:
df.isna().sum()

id                    0
gender                0
age                   0
race_ethnicity        0
education          4139
bmi                3462
height_cm          3434
systolic_bp        4416
has_diabetes        193
hba1c              5218
fasting_glucose    8261
dtype: int64

In [48]:
df.isna().mean() * 100

id                  0.000000
gender              0.000000
age                 0.000000
race_ethnicity      0.000000
education          34.685326
bmi                29.011984
height_cm          28.777340
systolic_bp        37.006620
has_diabetes        1.617364
hba1c              43.727478
fasting_glucose    69.228191
dtype: float64

In [49]:
# Drop the rows where has_diabetes is missing
df_clean = df.dropna(subset=['has_diabetes']).copy()

# Check how many rows you lost
print(f"Started with {len(df)} rows")
print(f"Now have {len(df_clean)} rows")

Started with 11933 rows
Now have 11740 rows

In [50]:
#Fill in missing systolic_bp with mean
mean_bp = df_clean['systolic_bp'].mean()
df_clean['systolic_bp'] = df_clean['systolic_bp'].fillna(mean_bp)

In [51]:
# Check it worked - it should be 0 now
df_clean['systolic_bp'].isna().sum()

np.int64(0)

Transform variables

In [52]:
# Create BMI categories
df['bmi_category'] = pd.cut(df['bmi'],
                             bins=[0, 18.5, 25, 30, 100],
                             labels=['Underweight', 'Normal', 'Overweight', 'Obese'])

# Check if it worked
df['bmi_category'].value_counts()

bmi_category
Obese          2666
Normal         2400
Overweight     2189
Underweight    1216
Name: count, dtype: int64

In [53]:
df['education'].unique()

array([ 5.,  3., nan,  2.,  4.,  1.,  9.])

In [54]:
# Create a mapping dictionary (adjust based on my data)
education_map = {
    '1.0': 'Less than 9th grade',
    '2.0': '9-11th grade',
    '3.0': 'High school grad',
    '4.0': 'Some college or AA degree',
    '5.0': 'College graduate',
    '9.0': 'Do not know',
    'None': 'Missing'
}
# Now apply the mapping
df['education_label'] = df['education'].map(education_map)

In [55]:
# Check if it worked
df['education_label'].value_counts()

Series([], Name: count, dtype: int64)

# **Data Summarization**

Numeric

In [56]:
# Calculate mean
df['systolic_bp'].mean()

# Calculate standard deviation
df['systolic_bp'].std()

# now get both at once
df['systolic_bp'].describe()

count    7517.000000
mean      119.288546
std        18.561052
min        61.000000
25%       106.000000
50%       117.000000
75%       130.000000
max       232.000000
Name: systolic_bp, dtype: float64

In [57]:
# Median
df['age'].median()

37.0

In [58]:
# IQR - just the 25th and 75th percentiles
df['age'].quantile([0.25, 0.75])

0.25    13.0
0.75    62.0
Name: age, dtype: float64

In [59]:
# now all at once
df['age'].describe()

count    1.193300e+04
mean     3.831786e+01
std      2.560199e+01
min      5.397605e-79
25%      1.300000e+01
50%      3.700000e+01
75%      6.200000e+01
max      8.000000e+01
Name: age, dtype: float64

In [60]:
df['age'].mode()

0    80.0
Name: age, dtype: float64

Categorical

One Variable

In [61]:
# Simple counts
df['education_label'].value_counts()

Series([], Name: count, dtype: int64)

In [62]:
# now with percentages
df['education_label'].value_counts(normalize=True) * 100

Series([], Name: proportion, dtype: float64)

Categorical

Two Variables

In [63]:
# Create a cross-tabulation
pd.crosstab(df['has_diabetes'], df['bmi_category'])

bmi_category  Underweight  Normal  Overweight  Obese
has_diabetes
1.0                     4     109         233    504
2.0                  1211    2251        1886   2042
3.0                     0      39          70    120
9.0                     1       1           0      0

In [64]:
# Rows with percentages (useful for clinicals)
pd.crosstab(df['has_diabetes'], df['bmi_category'], normalize='index') * 100

bmi_category  Underweight     Normal  Overweight      Obese
has_diabetes
1.0              0.470588  12.823529   27.411765  59.294118
2.0             16.387009  30.460081   25.520974  27.631935
3.0              0.000000  17.030568   30.567686  52.401747
9.0             50.000000  50.000000    0.000000   0.000000

Mix of variables

In [65]:
#df.groupby('grouping_variable')['numeric_variable'].calculation()
df.groupby('has_diabetes')['bmi'].mean()

has_diabetes
1.0    32.981412
2.0    26.439797
3.0    32.068559
9.0    19.250000
Name: bmi, dtype: float64